//
//  LumenTokens.swift
//  Lumen v0.13 — semantic token constants for iOS.
//
//  In production, this file is generated by Style Dictionary into
//  dist/swift/Lumen+Colors.swift and dist/ios/LumenTokens.swift. The reference
//  inlines the subset the three surfaces need so the package compiles standalone.
//
//  Source of truth: design-system/01-tokens/{primitives,semantic,modes}/*.tokens.json
//

import SwiftUI

public enum LumenColors {
    // Surface
    public static let surfaceCanvas = Color(red: 0.051, green: 0.051, blue: 0.051)    // #0D0D0D
    public static let surfaceRaised = Color(red: 0.090, green: 0.090, blue: 0.090)    // #171717
    public static let surfaceSunken = Color(red: 0.039, green: 0.039, blue: 0.039)    // #0A0A0A
    public static let surfaceGlassTint = Color(red: 0.051, green: 0.051, blue: 0.051).opacity(0.5)

    // Text
    public static let textPrimary   = Color(red: 0.980, green: 0.980, blue: 0.980)    // #FAFAFA
    public static let textSecondary = Color(red: 0.651, green: 0.651, blue: 0.651)    // #A6A6A6
    public static let textTertiary  = Color(red: 0.451, green: 0.451, blue: 0.451)    // #737373
    public static let textAccent    = Color(red: 0.000, green: 0.980, blue: 0.541)    // #00FA8A

    // Border
    public static let borderHairline = Color.white.opacity(0.06)
    public static let borderDefault  = Color.white.opacity(0.18)
    public static let borderStrong   = Color.white.opacity(0.24)
    public static let borderAccent   = Color(red: 0.000, green: 0.980, blue: 0.541).opacity(0.4)
    public static let borderFocus    = Color(red: 0.000, green: 0.980, blue: 0.541)
    public static let borderFrame    = Color.white.opacity(0.12)

    // Action
    public static let actionPrimaryBgRest  = Color(red: 0.000, green: 0.980, blue: 0.541)  // #00FA8A
    public static let actionPrimaryBgHover = Color(red: 0.000, green: 0.839, blue: 0.459)  // #00D675
    public static let actionPrimaryBgPress = Color(red: 0.000, green: 0.690, blue: 0.384)  // #00B062
    public static let actionPrimaryFg      = Color(red: 0.027, green: 0.071, blue: 0.051)  // #07120D — hard rule 9
}

public enum LumenDuration {
    public static let micro: Double = 0.08
    public static let fast:  Double = 0.14
    public static let base:  Double = 0.20
    public static let slow:  Double = 0.32
    public static let slower: Double = 0.48
}

public enum LumenEasing {
    /// Lumen default — 95% of moments. From design-system/01-tokens/primitives/motion.tokens.json.
    public static let decelerate: Animation = .timingCurve(0.2, 0, 0, 1, duration: LumenDuration.base)
    public static let micro:       Animation = .timingCurve(0.2, 0, 0, 1, duration: LumenDuration.micro)
    public static let fast:        Animation = .timingCurve(0.2, 0, 0, 1, duration: LumenDuration.fast)
}

public enum LumenSpring {
    /// Lumen default spring — k=280, d=28, m=1. SwiftUI parameterization.
    public static let `default`: Animation = .spring(response: 0.38, dampingFraction: 0.84)
    /// Lumen gentle spring — k=200, d=32, m=1. Critically damped.
    public static let gentle:    Animation = .spring(response: 0.44, dampingFraction: 1.0)
}

public enum LumenRadius {
    public static let xs: CGFloat = 3
    public static let sm: CGFloat = 4
    public static let md: CGFloat = 6
    public static let lg: CGFloat = 12
    public static let xl: CGFloat = 16
}

public enum LumenSpacing {
    public static let s1: CGFloat = 4
    public static let s2: CGFloat = 8
    public static let s3: CGFloat = 12
    public static let s4: CGFloat = 16
    public static let s5: CGFloat = 20
    public static let s6: CGFloat = 24
}

public enum LumenFont {
    /// The single Lumen typeface. Bundle Satoshi-Variable.otf + Italic into the app target.
    public static let name = "Satoshi-Variable"
    public static let italicName = "Satoshi-VariableItalic"

    public static func body(_ size: CGFloat = 14) -> Font {
        Font.custom(name, size: size)
    }
    public static func bold(_ size: CGFloat) -> Font {
        Font.custom(name, size: size).weight(.bold)
    }
}
