//
//  LumenTypography.swift
//  Lumen v0.13.4 — composite typography helpers for iOS / SwiftUI.
//
//  Closes chat 14's v0.14 candidate: helper functions on iOS + Compose for
//  composite typography. Consumers no longer have to compose
//  `Font.system(size:weight:design:)` from atomic primitives by hand — the
//  composite roles (display, heading, body, caption, mono) ship as static
//  Font properties on `LumenFont`.
//
//  Atomic primitives still live in dist/swift/Lumen+Typography.swift (auto-
//  generated by Style Dictionary). This file COMPOSES those atoms into the
//  Lumen-canonical role set: display.{hero,2xl,xl,lg,md} · heading.{h1..h6} ·
//  body.{lg,md,sm} · caption · mono.{cap,code}.
//
//  Values come from the v0.12 typography ramp (locked since v0.10):
//
//    Role            size  weight     line-height  tracking  features
//    display.hero    128   bold       1.05         -0.04em   tnum,case,ss01
//    display.2xl     96    bold       1.05         -0.03em   tnum,case
//    display.xl      72    bold       1.10         -0.02em   tnum,case
//    display.lg      56    bold       1.10         -0.02em   tnum
//    display.md      40    bold       1.15         -0.01em   tnum
//    heading.h1      40    semibold   1.20          0        case
//    heading.h2      32    semibold   1.25          0        case
//    heading.h3      24    semibold   1.30          0        case
//    heading.h4      20    semibold   1.35          0        case
//    heading.h5      18    semibold   1.40          0
//    heading.h6      16    semibold   1.45          0
//    body.lg         18    regular    1.55          0
//    body.md         16    regular    1.55          0
//    body.sm         14    regular    1.50          0
//    caption         12    medium     1.45          0.02em
//    mono.cap        11    medium     1.40          0.16em   tnum,case,calt-off
//    mono.code       13    regular    1.55          0        tnum,zero,calt-off
//
//  SwiftUI's `.font(.system(...))` doesn't expose tracking / OpenType features
//  directly — for those, consumers reach for `.tracking(_:)` and `.fontFeatureSetting`.
//  This file ships the size/weight composites; tracking + features are documented
//  as separate modifier-chain extensions below.
//

import SwiftUI

/// Composite typography helpers — every role from the v0.12 typography ramp,
/// pre-composed into `Font` instances ready to drop into a `.font(...)` modifier.
public enum LumenFont {
    // MARK: - Display (hero, marketing surface)

    public static let displayHero = Font.system(size: 128, weight: .bold, design: .default)
    public static let display2xl  = Font.system(size: 96,  weight: .bold, design: .default)
    public static let displayXL   = Font.system(size: 72,  weight: .bold, design: .default)
    public static let displayLG   = Font.system(size: 56,  weight: .bold, design: .default)
    public static let displayMD   = Font.system(size: 40,  weight: .bold, design: .default)

    // MARK: - Heading (page chrome, section heads)

    public static let h1 = Font.system(size: 40, weight: .semibold, design: .default)
    public static let h2 = Font.system(size: 32, weight: .semibold, design: .default)
    public static let h3 = Font.system(size: 24, weight: .semibold, design: .default)
    public static let h4 = Font.system(size: 20, weight: .semibold, design: .default)
    public static let h5 = Font.system(size: 18, weight: .semibold, design: .default)
    public static let h6 = Font.system(size: 16, weight: .semibold, design: .default)

    // MARK: - Body (paragraph, UI labels)

    public static let bodyLG = Font.system(size: 18, weight: .regular, design: .default)
    public static let bodyMD = Font.system(size: 16, weight: .regular, design: .default)
    public static let bodySM = Font.system(size: 14, weight: .regular, design: .default)

    // MARK: - Caption (small, supporting copy)

    public static let caption = Font.system(size: 12, weight: .medium, design: .default)

    // MARK: - Mono (uppercase tracked label + code)

    /// Mono-uppercase tracked label. Combine with `.tracking(_:)` modifier — Lumen's
    /// canonical tracking is 0.16em (≈ 1.76 at 11pt).
    public static let monoCap = Font.system(size: 11, weight: .medium, design: .default)

    /// Code font. Satoshi with `tnum` + `zero`. Distinct from `code.fallback` which
    /// is Geist Mono — opt-in only per AGENTS.md hard rule §typography.
    public static let monoCode = Font.system(size: 13, weight: .regular, design: .default)
}

// MARK: - View modifier helpers for tracking + OpenType features

public extension View {
    /// Apply Lumen's mono-uppercase-tracked label voice: 0.16em tracking +
    /// uppercase + the mono.cap font role. Usage:
    ///
    ///     Text("SYSTEM V0.13 · LIVE")
    ///         .lumenMonoCap()
    func lumenMonoCap() -> some View {
        self.font(LumenFont.monoCap)
            .tracking(1.76)  // 0.16em at 11pt
            .textCase(.uppercase)
    }

    /// Apply Lumen's display-hero voice: 128pt bold + −0.04em tracking + tnum.
    /// Usage:
    ///
    ///     Text("Stop re-designing")
    ///         .lumenDisplayHero()
    func lumenDisplayHero() -> some View {
        self.font(LumenFont.displayHero)
            .tracking(-5.12)  // -0.04em at 128pt
    }
}
