// Lumen Button — Android Jetpack Compose example (v0.14)
//
// Native counterpart to /examples/primary.tsx. Mirrors the SwiftUI example
// (/examples/swiftui.swift) — same Lumen contract, expressed via Compose.
// Tokens come from _build/compose/LumenTokens.kt (generated by Style Dictionary).
// For demo purposes, the tokens are inlined below.

package design.warp.lumen.button.example

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.foundation.clickable
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.interaction.collectIsPressedAsState
import androidx.compose.runtime.remember
import androidx.compose.runtime.getValue
import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.ui.draw.scale

// MARK: - Tokens
object LumenTokens {
    object Colors {
        val SurfaceCanvas = Color(0xFF0D0D0D)       // #0D0D0D dark canvas
        val TextPrimary = Color(0xFFE6E6E6)         // #E6E6E6
        val TextOnAccent = Color(0xFF07120D)        // #07120D
        val Accent500 = Color(0xFF00FA8A)           // #00FA8A spring green
        val AccentHover = Color(0xFF0AFF93)         // #0AFF93
        val BorderDefault = Color(0xFF404040)       // #404040
        val Danger = Color(0xFFD32F2F)
    }
    object Radius {
        val ControlMd = 6.dp
    }
    object Sizes {
        val ControlSm = 32.dp
        val ControlMd = 40.dp
        val ControlLg = 48.dp
    }
}

// MARK: - Intent + Size
enum class LumenButtonIntent { PRIMARY, SECONDARY, GHOST, DANGER }
enum class LumenButtonSize { SM, MD, LG }

private fun heightFor(size: LumenButtonSize) = when (size) {
    LumenButtonSize.SM -> LumenTokens.Sizes.ControlSm
    LumenButtonSize.MD -> LumenTokens.Sizes.ControlMd
    LumenButtonSize.LG -> LumenTokens.Sizes.ControlLg
}

private fun horizontalPaddingFor(size: LumenButtonSize) = when (size) {
    LumenButtonSize.SM -> 12.dp
    LumenButtonSize.MD -> 16.dp
    LumenButtonSize.LG -> 20.dp
}

private fun fontSizeFor(size: LumenButtonSize) = when (size) {
    LumenButtonSize.SM -> 13.sp
    LumenButtonSize.MD -> 14.sp
    LumenButtonSize.LG -> 16.sp
}

// MARK: - LumenButton
@Composable
fun LumenButton(
    text: String,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
    intent: LumenButtonIntent = LumenButtonIntent.SECONDARY,
    size: LumenButtonSize = LumenButtonSize.MD,
    fullWidth: Boolean = false,
) {
    val interactionSource = remember { MutableInteractionSource() }
    val isPressed by interactionSource.collectIsPressedAsState()
    val scale by animateFloatAsState(targetValue = if (isPressed) 0.98f else 1.0f, label = "press-scale")

    val backgroundColor = when (intent) {
        LumenButtonIntent.PRIMARY -> if (isPressed) LumenTokens.Colors.AccentHover else LumenTokens.Colors.Accent500
        LumenButtonIntent.SECONDARY -> Color(0x2EFFFFFF) // gray.alpha(0.18)
        LumenButtonIntent.GHOST -> Color.Transparent
        LumenButtonIntent.DANGER -> LumenTokens.Colors.Danger
    }
    val textColor = when (intent) {
        LumenButtonIntent.PRIMARY -> LumenTokens.Colors.TextOnAccent
        LumenButtonIntent.SECONDARY, LumenButtonIntent.GHOST -> LumenTokens.Colors.TextPrimary
        LumenButtonIntent.DANGER -> Color.White
    }

    Box(
        modifier = modifier
            .then(if (fullWidth) Modifier.fillMaxWidth() else Modifier)
            .height(heightFor(size))
            .scale(scale)
            .background(backgroundColor, RoundedCornerShape(LumenTokens.Radius.ControlMd))
            .then(
                if (intent == LumenButtonIntent.GHOST) Modifier
                else Modifier.border(
                    1.dp,
                    LumenTokens.Colors.BorderDefault.copy(alpha = if (intent == LumenButtonIntent.PRIMARY) 0f else 0.6f),
                    RoundedCornerShape(LumenTokens.Radius.ControlMd)
                )
            )
            .padding(horizontal = horizontalPaddingFor(size))
            .clickable(
                interactionSource = interactionSource,
                indication = null,
                onClick = onClick,
            ),
        contentAlignment = Alignment.Center,
    ) {
        Text(
            text = text,
            color = textColor,
            fontSize = fontSizeFor(size),
            fontWeight = FontWeight.Medium,
        )
    }
}

// MARK: - Demo
@Preview(showBackground = true, backgroundColor = 0xFF0D0D0D)
@Composable
fun LumenButtonDemo() {
    Column(
        modifier = Modifier
            .background(LumenTokens.Colors.SurfaceCanvas)
            .padding(24.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp),
    ) {
        LumenButton("Primary action", onClick = {}, intent = LumenButtonIntent.PRIMARY)
        LumenButton("Secondary", onClick = {}, intent = LumenButtonIntent.SECONDARY)
        LumenButton("Ghost", onClick = {}, intent = LumenButtonIntent.GHOST)
        LumenButton("Delete", onClick = {}, intent = LumenButtonIntent.DANGER)
        LumenButton(
            "Large fullWidth CTA",
            onClick = {},
            intent = LumenButtonIntent.PRIMARY,
            size = LumenButtonSize.LG,
            fullWidth = true,
        )
    }
}
