// lumen-lint-allow-block: primitives — React Native example file. Native
// platforms (RN, iOS, Android) cannot reference CSS variables; tokens convert
// to hex literals at the platform-build step. The hex values mirror the
// canonical primitive token values from design-system/01-tokens/. Real consumer
// apps import from _build/react-native/tokens.ts instead of inlining.
// Lumen Button — React Native example (v0.14)
//
// Native counterpart to /examples/primary.tsx. The React Native build uses
// StyleSheet + Pressable for press feedback. Tokens come from
// _build/react-native/tokens.ts (generated by Style Dictionary). For demo
// purposes the values are inlined.
//
// Drop this file into your RN project at /components/lumen/Button.tsx.

import React, { useState } from "react";
import { Pressable, Text, View, StyleSheet, type PressableProps, type ViewStyle, type TextStyle } from "react-native";

// MARK: - Tokens
const LumenTokens = {
  color: {
    surfaceCanvas: "#0D0D0D",
    textPrimary: "#E6E6E6",
    textOnAccent: "#07120D",
    accent500: "#00FA8A",
    accentHover: "#0AFF93",
    borderDefault: "#404040",
    danger: "#D32F2F",
  },
  radius: {
    controlMd: 6,
  },
  size: {
    controlSm: 32,
    controlMd: 40,
    controlLg: 48,
  },
} as const;

// MARK: - Types
type LumenButtonIntent = "primary" | "secondary" | "ghost" | "danger";
type LumenButtonSize = "sm" | "md" | "lg";

type LumenButtonProps = Omit<PressableProps, "style"> & {
  label: string;
  intent?: LumenButtonIntent;
  size?: LumenButtonSize;
  fullWidth?: boolean;
  onPress: () => void;
};

// MARK: - Sizing
const heightFor = (size: LumenButtonSize) =>
  size === "sm" ? LumenTokens.size.controlSm : size === "lg" ? LumenTokens.size.controlLg : LumenTokens.size.controlMd;
const horizontalPaddingFor = (size: LumenButtonSize) => (size === "sm" ? 12 : size === "lg" ? 20 : 16);
const fontSizeFor = (size: LumenButtonSize) => (size === "sm" ? 13 : size === "lg" ? 16 : 14);

// MARK: - Background + foreground
function backgroundFor(intent: LumenButtonIntent, pressed: boolean) {
  switch (intent) {
    case "primary":
      return pressed ? LumenTokens.color.accentHover : LumenTokens.color.accent500;
    case "secondary":
      return "rgba(255,255,255,0.18)";
    case "ghost":
      return "transparent";
    case "danger":
      return LumenTokens.color.danger;
  }
}

function foregroundFor(intent: LumenButtonIntent) {
  switch (intent) {
    case "primary":
      return LumenTokens.color.textOnAccent;
    case "secondary":
    case "ghost":
      return LumenTokens.color.textPrimary;
    case "danger":
      return "#FFFFFF";
  }
}

// MARK: - LumenButton
export function LumenButton({
  label,
  intent = "secondary",
  size = "md",
  fullWidth = false,
  onPress,
  ...rest
}: LumenButtonProps) {
  const [pressed, setPressed] = useState(false);

  const containerStyle: ViewStyle = {
    height: heightFor(size),
    paddingHorizontal: horizontalPaddingFor(size),
    backgroundColor: backgroundFor(intent, pressed),
    borderRadius: LumenTokens.radius.controlMd,
    alignSelf: fullWidth ? "stretch" : "flex-start",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    transform: [{ scale: pressed ? 0.98 : 1.0 }],
    borderWidth: intent === "ghost" ? 0 : 1,
    borderColor: intent === "primary" ? "transparent" : LumenTokens.color.borderDefault,
  };

  const textStyle: TextStyle = {
    color: foregroundFor(intent),
    fontSize: fontSizeFor(size),
    fontWeight: "500",
  };

  return (
    <Pressable
      onPress={onPress}
      onPressIn={() => setPressed(true)}
      onPressOut={() => setPressed(false)}
      accessibilityRole="button"
      accessibilityLabel={label}
      style={containerStyle}
      {...rest}
    >
      <Text style={textStyle}>{label}</Text>
    </Pressable>
  );
}

// MARK: - Demo
export function LumenButtonDemo() {
  return (
    <View style={styles.demo}>
      <LumenButton label="Primary action" intent="primary" onPress={() => undefined} />
      <LumenButton label="Secondary" intent="secondary" onPress={() => undefined} />
      <LumenButton label="Ghost" intent="ghost" onPress={() => undefined} />
      <LumenButton label="Delete" intent="danger" onPress={() => undefined} />
      <LumenButton label="Large fullWidth CTA" intent="primary" size="lg" fullWidth onPress={() => undefined} />
    </View>
  );
}

const styles = StyleSheet.create({
  demo: {
    flex: 1,
    backgroundColor: LumenTokens.color.surfaceCanvas,
    padding: 24,
    gap: 16,
    alignItems: "flex-start",
  },
});
