// Lumen Button — iOS SwiftUI example (v0.14)
//
// Native counterpart to /examples/primary.tsx. The web React example uses
// CSS-class composition; SwiftUI mirrors the same contract via a ButtonStyle
// + the LumenTokens enum (generated from _build/ios/LumenTokens*.swift by
// Style Dictionary).
//
// This file is a starting point — copy it into your iOS app and adjust the
// LumenTokens import path to wherever the generated swift file lives.

import SwiftUI

// MARK: - Tokens
// In a real app these come from _build/ios/LumenTokens.swift (light) +
// LumenTokensDark.swift (dark), generated by Style Dictionary. For demo
// purposes we inline the v0.14 values.
enum LumenTokens {
    enum Color {
        static let surfaceCanvas = SwiftUI.Color(red: 0.051, green: 0.051, blue: 0.051) // #0D0D0D dark canvas
        static let textPrimary = SwiftUI.Color(red: 0.902, green: 0.902, blue: 0.902)    // #E6E6E6
        static let textOnAccent = SwiftUI.Color(red: 0.027, green: 0.071, blue: 0.051)   // #07120D
        static let accent500 = SwiftUI.Color(red: 0.0, green: 0.980, blue: 0.541)        // #00FA8A spring green
        static let accentHover = SwiftUI.Color(red: 0.039, green: 1.0, blue: 0.576)      // #0AFF93
        static let borderDefault = SwiftUI.Color(red: 0.251, green: 0.251, blue: 0.251)  // #404040
    }
    enum Radius {
        static let controlMd: CGFloat = 6
    }
    enum Size {
        static let controlSm: CGFloat = 32
        static let controlMd: CGFloat = 40
        static let controlLg: CGFloat = 48
    }
}

// MARK: - Intent + Size
enum LumenButtonIntent {
    case primary, secondary, ghost, danger
}

enum LumenButtonSize {
    case sm, md, lg

    var height: CGFloat {
        switch self {
        case .sm: return LumenTokens.Size.controlSm
        case .md: return LumenTokens.Size.controlMd
        case .lg: return LumenTokens.Size.controlLg
        }
    }

    var horizontalPadding: CGFloat {
        switch self {
        case .sm: return 12
        case .md: return 16
        case .lg: return 20
        }
    }
}

// MARK: - LumenButtonStyle
struct LumenButtonStyle: ButtonStyle {
    let intent: LumenButtonIntent
    let size: LumenButtonSize
    let fullWidth: Bool

    init(intent: LumenButtonIntent = .secondary, size: LumenButtonSize = .md, fullWidth: Bool = false) {
        self.intent = intent
        self.size = size
        self.fullWidth = fullWidth
    }

    func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .font(.system(size: bodyFontSize(for: size), weight: .medium))
            .padding(.horizontal, size.horizontalPadding)
            .frame(maxWidth: fullWidth ? .infinity : nil)
            .frame(height: size.height)
            .background(backgroundColor(configuration: configuration))
            .foregroundStyle(foregroundColor)
            .clipShape(RoundedRectangle(cornerRadius: LumenTokens.Radius.controlMd, style: .continuous))
            .overlay(border(configuration: configuration))
            .scaleEffect(configuration.isPressed ? 0.98 : 1.0)
            .animation(.easeOut(duration: 0.12), value: configuration.isPressed)
    }

    private func bodyFontSize(for size: LumenButtonSize) -> CGFloat {
        switch size {
        case .sm: return 13
        case .md: return 14
        case .lg: return 16
        }
    }

    private func backgroundColor(configuration: Configuration) -> some View {
        let base: SwiftUI.Color
        switch intent {
        case .primary: base = configuration.isPressed ? LumenTokens.Color.accentHover : LumenTokens.Color.accent500
        case .secondary: base = .gray.opacity(0.18)
        case .ghost: base = .clear
        case .danger: base = SwiftUI.Color(red: 0.83, green: 0.18, blue: 0.18)
        }
        return base
    }

    private var foregroundColor: SwiftUI.Color {
        switch intent {
        case .primary: return LumenTokens.Color.textOnAccent
        case .secondary, .ghost: return LumenTokens.Color.textPrimary
        case .danger: return .white
        }
    }

    @ViewBuilder
    private func border(configuration: Configuration) -> some View {
        if intent == .ghost {
            EmptyView()
        } else {
            RoundedRectangle(cornerRadius: LumenTokens.Radius.controlMd, style: .continuous)
                .stroke(LumenTokens.Color.borderDefault.opacity(intent == .primary ? 0 : 0.6), lineWidth: 1)
        }
    }
}

// MARK: - Demo
struct LumenButtonDemo: View {
    var body: some View {
        VStack(spacing: 16) {
            Button("Primary action") {}
                .buttonStyle(LumenButtonStyle(intent: .primary, size: .md))
            Button("Secondary") {}
                .buttonStyle(LumenButtonStyle(intent: .secondary, size: .md))
            Button("Ghost") {}
                .buttonStyle(LumenButtonStyle(intent: .ghost, size: .md))
            Button("Delete") {}
                .buttonStyle(LumenButtonStyle(intent: .danger, size: .md))
            Button("Large fullWidth CTA") {}
                .buttonStyle(LumenButtonStyle(intent: .primary, size: .lg, fullWidth: true))
        }
        .padding(24)
        .background(LumenTokens.Color.surfaceCanvas.ignoresSafeArea())
        .preferredColorScheme(.dark)
    }
}

#Preview {
    LumenButtonDemo()
}
