/*
 * LumenTypography.kt
 * Lumen v0.13.4 — composite typography helpers for Android / Jetpack Compose.
 *
 * Closes chat 14's v0.14 candidate: helper functions on iOS + Compose for
 * composite typography. Consumers no longer have to compose
 * `TextStyle(fontSize:, fontWeight:, lineHeight:)` from atomic primitives by
 * hand — the composite roles (display, heading, body, caption, mono) ship as
 * top-level vals on `LumenTextStyles`.
 *
 * Atomic primitives still live in dist/compose/LumenTypography.kt (auto-
 * generated by Style Dictionary). This file COMPOSES those atoms into the
 * Lumen-canonical role set: display.{hero,2xl,xl,lg,md} · heading.{h1..h6} ·
 * body.{lg,md,sm} · caption · mono.{cap,code}.
 *
 * Values come from the v0.12 typography ramp (locked since v0.10).
 *
 * Compose's `TextStyle` exposes fontSize, fontWeight, lineHeight, letterSpacing
 * directly — so every role is fully composable here. OpenType feature flags
 * (tnum, zero, case, ss01-04) require `FontFeatureSetting` from Compose's
 * Paragraph layer; they're applied per-Text-call via the `style` parameter's
 * `paragraphStyle.fontFeatureSettings`. See the helpers at the bottom.
 *
 * Package matches the auto-generated LumenTypography.kt: dev.warp.lumen.
 */

package dev.warp.lumen

import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextDecoration
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp

/**
 * Composite typography roles — every role from the v0.12 typography ramp,
 * pre-composed into `TextStyle` instances ready for `Text(..., style = ...)`.
 *
 * All roles use `LumenFontFamily.satoshi` by default. If the consumer hasn't
 * bundled Satoshi-Variable.ttf yet, the FontFamily falls back to the system
 * sans-serif (system-ui on Android 11+).
 */
object LumenTextStyles {
    // ---------- Display (hero, marketing) ----------

    val displayHero = TextStyle(
        fontSize = 128.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = (128 * 1.05).sp,
        letterSpacing = (-0.04).em,
        fontFamily = LumenFontFamily.satoshi,
    )

    val display2xl = TextStyle(
        fontSize = 96.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = (96 * 1.05).sp,
        letterSpacing = (-0.03).em,
        fontFamily = LumenFontFamily.satoshi,
    )

    val displayXL = TextStyle(
        fontSize = 72.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = (72 * 1.10).sp,
        letterSpacing = (-0.02).em,
        fontFamily = LumenFontFamily.satoshi,
    )

    val displayLG = TextStyle(
        fontSize = 56.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = (56 * 1.10).sp,
        letterSpacing = (-0.02).em,
        fontFamily = LumenFontFamily.satoshi,
    )

    val displayMD = TextStyle(
        fontSize = 40.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = (40 * 1.15).sp,
        letterSpacing = (-0.01).em,
        fontFamily = LumenFontFamily.satoshi,
    )

    // ---------- Heading (page chrome) ----------

    val h1 = TextStyle(
        fontSize = 40.sp, fontWeight = FontWeight.SemiBold,
        lineHeight = (40 * 1.20).sp, fontFamily = LumenFontFamily.satoshi,
    )
    val h2 = TextStyle(
        fontSize = 32.sp, fontWeight = FontWeight.SemiBold,
        lineHeight = (32 * 1.25).sp, fontFamily = LumenFontFamily.satoshi,
    )
    val h3 = TextStyle(
        fontSize = 24.sp, fontWeight = FontWeight.SemiBold,
        lineHeight = (24 * 1.30).sp, fontFamily = LumenFontFamily.satoshi,
    )
    val h4 = TextStyle(
        fontSize = 20.sp, fontWeight = FontWeight.SemiBold,
        lineHeight = (20 * 1.35).sp, fontFamily = LumenFontFamily.satoshi,
    )
    val h5 = TextStyle(
        fontSize = 18.sp, fontWeight = FontWeight.SemiBold,
        lineHeight = (18 * 1.40).sp, fontFamily = LumenFontFamily.satoshi,
    )
    val h6 = TextStyle(
        fontSize = 16.sp, fontWeight = FontWeight.SemiBold,
        lineHeight = (16 * 1.45).sp, fontFamily = LumenFontFamily.satoshi,
    )

    // ---------- Body ----------

    val bodyLG = TextStyle(
        fontSize = 18.sp, fontWeight = FontWeight.Normal,
        lineHeight = (18 * 1.55).sp, fontFamily = LumenFontFamily.satoshi,
    )
    val bodyMD = TextStyle(
        fontSize = 16.sp, fontWeight = FontWeight.Normal,
        lineHeight = (16 * 1.55).sp, fontFamily = LumenFontFamily.satoshi,
    )
    val bodySM = TextStyle(
        fontSize = 14.sp, fontWeight = FontWeight.Normal,
        lineHeight = (14 * 1.50).sp, fontFamily = LumenFontFamily.satoshi,
    )

    // ---------- Caption ----------

    val caption = TextStyle(
        fontSize = 12.sp,
        fontWeight = FontWeight.Medium,
        lineHeight = (12 * 1.45).sp,
        letterSpacing = 0.02.em,
        fontFamily = LumenFontFamily.satoshi,
    )

    // ---------- Mono (uppercase tracked label + code) ----------

    /**
     * Mono-uppercase tracked label. Pair with `text = label.uppercase()` —
     * Compose doesn't have a CSS-style `text-transform: uppercase`, so the
     * uppercase transform happens in the caller.
     */
    val monoCap = TextStyle(
        fontSize = 11.sp,
        fontWeight = FontWeight.Medium,
        lineHeight = (11 * 1.40).sp,
        letterSpacing = 0.16.em,
        fontFamily = LumenFontFamily.satoshi,
        fontFeatureSettings = "tnum, case, calt off",
    )

    /**
     * Code font. Satoshi with `tnum` + `zero`. For Geist Mono (the `code.fallback`
     * alias), substitute LumenFontFamily.geistMono — opt-in per AGENTS.md.
     */
    val monoCode = TextStyle(
        fontSize = 13.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = (13 * 1.55).sp,
        fontFamily = LumenFontFamily.satoshi,
        fontFeatureSettings = "tnum, zero, calt off",
    )
}

/**
 * FontFamily aliases for Lumen. Consumers must bundle the Satoshi-Variable.ttf
 * font asset (ITF-FFL, self-host only — must NOT redistribute in a public
 * repo per AGENTS.md). Place at `res/font/satoshi_variable.ttf`.
 *
 * Without the asset, Compose falls back to FontFamily.SansSerif (system-ui).
 */
object LumenFontFamily {
    // Replace with FontFamily(Font(R.font.satoshi_variable, weight = FontWeight.Normal))
    // once the asset ships. The reference app uses system fallback.
    val satoshi: FontFamily = FontFamily.SansSerif

    /** Geist Mono — the v0.13 code.fallback alias. Opt-in only. */
    val geistMono: FontFamily = FontFamily.Monospace
}
