// swift-tools-version: 5.10
//
// LumenReference — iOS reference app for Lumen v0.13.
// Renders three surfaces: primary button, stat, glass popover.
// Demonstrates the iOS translation contract from design-system/04-platforms/ios.md.

import PackageDescription

let package = Package(
    name: "LumenReference",
    platforms: [
        .iOS(.v17),
    ],
    products: [
        .executable(name: "LumenReferenceApp", targets: ["LumenReferenceApp"]),
        .library(name: "LumenTokens", targets: ["LumenTokens"]),
    ],
    dependencies: [],
    targets: [
        // LumenTokens — generated by Style Dictionary into dist/swift/Lumen+Colors.swift
        // + dist/ios/LumenTokens.swift. In a real Swift Package distribution this target
        // copies those generated files. The reference app vendors the relevant constants
        // inline for portability.
        .target(
            name: "LumenTokens",
            path: "Sources/LumenTokens"
        ),
        // The reference app target.
        .executableTarget(
            name: "LumenReferenceApp",
            dependencies: ["LumenTokens"],
            path: "Sources/LumenReferenceApp",
            resources: [
                .copy("Resources/Satoshi-Variable.woff2.placeholder"),
                // In production, ship Satoshi-Variable.otf and -VariableItalic.otf as
                // .process resources and register via Info.plist's UIAppFonts.
            ]
        ),
    ]
)
