#!/usr/bin/env node
// Subset Satoshi-Variable.woff2 + Satoshi-VariableItalic.woff2 for the
// audit-dashboard's deployed surface area.
//
// Coverage policy (v0.13.4, R8a):
//   ASCII + Latin-1 supplement (Western European accented Latin)
//   + General Punctuation (em dash, en dash, smart quotes, ellipsis, bullet)
//   + Currency Symbols (€, £, ¥, ₹, $, etc.)
//   + Letterlike Symbols (©, ®, ™, ℗, ℠, ℅, ℉, ℃, …)
//   + Arrows (↑ ↓ ← →)
//   + Used Math operators (− ∞ ≈ ≠ ≤ ≥ ÷ ×)
//   + ✓ (dingbat checkmark)
//   +
//
// Drops (intentionally — fall through to system fallback if needed):
//   Latin Extended-A (Eastern European: Polish, Czech, Hungarian, Romanian, Turkish)
//   Latin Extended-B
//   IPA Extensions / Spacing modifiers
//   Combining diacritics (the Latin-1 precomposed forms cover the common chars)
//   Greek (Ω, π — drop the 2 we shipped; fall to fallback fine)
//   Box drawing / geometric shapes (drop the 8 we had)
//
// All OpenType features (kern, liga, calt, ss01-ss04, tnum, lnum, case, frac)
// stay — the design system's typography ladder + globals.css mono utilities
// reference them.
//
// Variable axis (wght 300-900) is preserved — Lumen's weight ladder spans the
// full range.
//
// Output: in-place overwrite of the two woff2 files. Run pre-commit if you
// touch the keep set so the diff is captured atomically with the audit-runs/
// closeout doc.
//
// Verification: after running, re-build (`cd audit-dashboard && pnpm build`)
// and re-run the R8a Lighthouse script.

import { spawnSync } from "node:child_process";
import { existsSync, statSync, copyFileSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";

const repoRoot = resolve(import.meta.dirname, "..");
const fontDir = resolve(repoRoot, "audit-dashboard/src/fonts");
const backupDir = resolve(repoRoot, ".audit-runs/_font-backups");

const PRE_SUBSET = {
  regular: resolve(fontDir, "Satoshi-Variable.woff2"),
  italic: resolve(fontDir, "Satoshi-VariableItalic.woff2"),
};

const POST_SUBSET = {
  regular: resolve(fontDir, "Satoshi-Variable.woff2"),
  italic: resolve(fontDir, "Satoshi-VariableItalic.woff2"),
};

// Keep set — see policy comment above.
// Generated by `python3 -c "..."` in the v0.13.4 R8a discovery pass.
// Codepoints are listed individually so the diff is auditable.
const keepRanges = [
  [0x0020, 0x007E], // ASCII printable
  [0x00A0, 0x00FF], // Latin-1 supplement
  [0x2010, 0x2027], // General Punctuation (dashes, quotes, ellipsis, bullet)
  [0x2030, 0x204F], // ‰, ‹›, †, ‡, etc. (mid-range punctuation)
  [0x20A0, 0x20CF], // Currency Symbols
  [0x2100, 0x214F], // Letterlike Symbols (©™®℗)
  [0x2190, 0x2194], // Basic arrows ↑ ↓ ← → ↔
  [0x25A0, 0x25CF], // Geometric shapes (■ □ ▲ △ ◊ ○ ●) — used by Stat / Charts / RateTicker / Nav stepper / Phone-frame status
];

const keepIndividual = [
  0x2212, 0x221E, 0x2248, 0x2260, 0x2264, 0x2265, // Math: − ∞ ≈ ≠ ≤ ≥
  0x2713,                                         // ✓ check
  0xF8FF,                                         //  Apple PUA logo
];

const keep = new Set(keepIndividual);
for (const [start, end] of keepRanges) {
  for (let c = start; c <= end; c++) keep.add(c);
}

const unicodesArg = [...keep].sort((a, b) => a - b).map((c) => `U+${c.toString(16).toUpperCase().padStart(4, "0")}`).join(",");

mkdirSync(backupDir, { recursive: true });

function backup(srcPath) {
  const ts = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  const base = srcPath.split("/").pop();
  const dest = resolve(backupDir, `${base}.${ts}.bak`);
  copyFileSync(srcPath, dest);
  return dest;
}

function runSubset(input, output) {
  // Use fontTools.subset via python3 -m fontTools.subset
  const args = [
    "-m", "fontTools.subset",
    input,
    `--unicodes=${unicodesArg}`,
    "--flavor=woff2",
    "--layout-features=*",                  // keep all OT features
    "--name-IDs=*",                         // keep all name records
    "--name-languages=*",                   // keep all language tags
    "--notdef-glyph",
    "--notdef-outline",
    "--ignore-missing-glyphs",
    `--output-file=${output}`,
  ];
  const result = spawnSync("python3", args, { stdio: "inherit" });
  if (result.status !== 0) {
    throw new Error(`fontTools subset failed for ${input}: exit ${result.status}`);
  }
}

const summary = [];
for (const [label, input] of Object.entries(PRE_SUBSET)) {
  if (!existsSync(input)) {
    console.error(`Missing input: ${input}`);
    process.exit(1);
  }
  const preSize = statSync(input).size;
  const backupPath = backup(input);
  const output = POST_SUBSET[label];
  // Write to a temp file first, then atomically overwrite the input
  const tempOut = `${output}.tmp`;
  runSubset(input, tempOut);
  // Atomic replace
  const fs = await import("node:fs");
  fs.renameSync(tempOut, output);
  const postSize = statSync(output).size;
  const delta = preSize - postSize;
  const pct = (1 - postSize / preSize) * 100;
  summary.push({ label, pre: preSize, post: postSize, delta, pct: pct.toFixed(1), backup: backupPath });
}

console.log("\n--- Satoshi subset results (R8a / v0.13.4) ---");
console.log(`Kept codepoint set: ${keep.size} codepoints`);
console.log();
for (const s of summary) {
  console.log(
    `${s.label.padEnd(8)}: ${s.pre.toString().padStart(6)} → ${s.post.toString().padStart(6)} bytes  ` +
    `(−${s.delta} bytes, ${s.pct}% smaller)  backup: ${s.backup.split("/").pop()}`
  );
}
const totalPre = summary.reduce((a, s) => a + s.pre, 0);
const totalPost = summary.reduce((a, s) => a + s.post, 0);
console.log(`\nTotal: ${totalPre} → ${totalPost} bytes (−${totalPre - totalPost} = ${(1 - totalPost / totalPre) * 100 .toFixed(1)}% reduction)`);
